### ISSUE TITLE
does it display arabic equations from right to left and with arabic-hindo numeric ?

### ISSUE THREAD

**Issue by osman-mohamad** [HosseinAgha/persian-katex-plugin#3]
does it display arabic equations from right to left and with arabic-hindo numeric ?

**Comment by HosseinAgha** [comment]
No I haven’t tested the rtl formulas.
Yes it adds persian-arabic numerals in formulas and arabic characters in ‘\text’ envs.

**Comment by osman-mohamad** [comment]
this mathjax plugin support translate letters to arabic chars and numbers . and flip the equation to be from right to left.

do you know how to do it in katex ?

thank you

**Comment by HosseinAgha** [comment]
I'm familiar with the [arabic-mathjax](https://edraak.github.io/arabic-mathjax/testcases/) and I think we can make it work with a little effort.  
- The main issue is that we need to add some macros to KaTeX in order to support things like `نهــا` in the math mode. And I'm not sure what they'll look like after macro transformation (We need to add some more UI tests). So If you are using `lim` and latin variables in your Arabic formulas you can easily use this (and even change the font to a more Arabic one like [Noto Arabic](https://www.google.com/get/noto/#naskh-arab)).   
- I'm not sure converting variables to their Arabic equivalent (e.g. `b` to `ب`) is a good idea but maybe you guys are used to writing the formulas in latin and getting an Arabic render.
- Another challenge is that this plugin does not impact latin formulas and same instance of KaTeX with this plugin loaded can also render latin formulas. But if we use macros in Arabic plugin to change `lim` to `نهــا` you're essentially ruining the latin renderer of KaTeX. So we may need to make some changes in the KaTeX to make plugins side effects to impact each `new KaTeX()` instance instead of the whole library.  
I wanted to fork this repo and make a `arabic-katex-plugin` but currently don't have bandwidth for that.  
Pinging @kevinbarabash as I think Khan was working on this.

**Comment by HosseinAgha** [comment]
Currently this formula `\text{أ} \rightarrow \text{ب}` renders to this:  
![image](https://user-images.githubusercontent.com/12998499/68105604-4e430080-fef4-11e9-9c97-301f18448228.png)

**Comment by osman-mohamad** [comment]
- currently arabic-mathjax work fine (mostly) . but mathjax generally is slower than katex . so I thought to try to use it instead of mathjax.

> So If you are using lim and Latin variables in your Arabic formulas you can easily use this

normally we do not use Latin variables in our math formulas . this is why I asked to translate some Latin functions like `lim` and characters to arabic . 

 > I'm not sure converting variables to their Arabic equivalent (e.g. b to ب) is a good idea but maybe you guys are used to writing the formulas in latin and getting an Arabic render.

No , we are not used to it . but it is simpler than writing arabic chars in Latin Equation . the Equation text become messy . so it will be simpler to use only Latin chars in our editors to simplify using Latex Equation.

> Another challenge is that this plugin does not impact Latin formulas and same instance of KaTeX ....

sorry I am expert in knowing the inside use of this libs . so I did not fully understand you.

about @kevinbarabash . he wrote about the arabic-mathjax plugin in issue . but there is no sign about any development in that issue. 

-------
In general I use Mathjax (or in this case Katex) to render math, physics, chem equations.
so, some times I need to render only Latin equations. and other times only arabic equations.

thank you for your time.

**Comment by k4b7** [comment]
We were working on as part of a hackathon project last year.  Unfortunately, no resourcing has been allocated to continue the project at the current time.

**Comment by osman-mohamad** [comment]
@kevinbarabash do you have it as public git repository ?

**Comment by HosseinAgha** [comment]
I am closing this as I think it is out of this project's scope. You can implement Arabic RTL formulas in another plugin.
